// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// C_get_dag_scores
Rcpp::List C_get_dag_scores(Rcpp::NumericMatrix dataset, Rcpp::NumericMatrix adj_matrix, double epos, double eneg);
RcppExport SEXP TRONCO_C_get_dag_scores(SEXP datasetSEXP, SEXP adj_matrixSEXP, SEXP eposSEXP, SEXP enegSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dataset(datasetSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type adj_matrix(adj_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type epos(eposSEXP);
    Rcpp::traits::input_parameter< double >::type eneg(enegSEXP);
    rcpp_result_gen = Rcpp::wrap(C_get_dag_scores(dataset, adj_matrix, epos, eneg));
    return rcpp_result_gen;
END_RCPP
}
