# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' execute the bootstrap procedure
#' 
#' @param x A single integer.
C_bootstrap <- function(x) {
    .Call('TRONCO_C_bootstrap', PACKAGE = 'TRONCO', x)
}

