# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' execute the get.dag.scores procedures
#' 
#' @param dataset A TRONCO dataset
#' @param adj_matrix An adj matrix
#' @param epos false positive rates
#' @param eneg false negative rates
C_get_dag_scores <- function(dataset, adj_matrix, epos, eneg) {
    .Call('TRONCO_C_get_dag_scores', PACKAGE = 'TRONCO', dataset, adj_matrix, epos, eneg)
}

