# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' execute the bootstrap procedure
#' 
#' @param x A single integer.
C_bootstrap <- function(A, x) {
    .Call('TRONCO_C_bootstrap', PACKAGE = 'TRONCO', A, x)
}

C_get_dag_scores <- function(dataset, adj_matrix, epos, eneg) {
    .Call('TRONCO_C_get_dag_scores', PACKAGE = 'TRONCO', dataset, adj_matrix, epos, eneg)
}

